# Draw phylogenetic trees generated by IQ-Tree using ggtree

library(ape)
library(tidyverse)
library(ggtree)
library(ggexpand)
library(treeio)
library(magrittr)
library(rcartocolor)
library(Cairo)

treefile <- file.choose()
tree <- read.iqtree(treefile)

tree_tbl <- as_tibble(tree)
Ce_nodes <- dplyr::filter(tree_tbl, grepl('Ce|DAF',label))
Str_nodes <- dplyr::filter(tree_tbl, grepl('SRAE|SSTP',label))
Sr_nodes <- dplyr::filter(tree_tbl, grepl('SRAE',label))
Ss_nodes <- dplyr::filter(tree_tbl, grepl('SSTP',label))
grp <- list (Elegans = Ce_nodes$node,
             Strongyloides = Str_nodes$node)
grp2 <- list (Elegans = Ce_nodes$node,
              Stercoralis = Ss_nodes$node,
              Ratti = Sr_nodes$node)
speciescolors <- c("Elegans" = "olivedrab", 
                   "Stercoralis" = "coral",
                   "Ratti" = "darkorchid")

p <- ggtree(tree, layout = "circular") +
    geom_tiplab(size = 2, hjust = -.05) + 
    geom_cladelabel(node = 134, label = "AFD-specific rGCs", align = T, offset = 1.2,
                    offset.text = .3, barsize = 1, angle = -4,
                    hjust = 'center', fontsize = 3) +
    #geom_hilight(node=86, fill="grey", alpha=.5, extend = 3) +
    xlim(0, 6)

# p2 <- groupOTU(p, grp, 'Species') + aes(color = Species) +
#     scale_color_carto_d(palette = "Vivid")

p3 <- groupOTU(p, grp2, 'Species') + aes(color = Species) +
    scale_color_manual(values = speciescolors)

# ggsave(plot = p2,
#        filename ="rGC_tree.pdf",
#        device = cairo_pdf,
#        width = 7)

ggsave(plot = p3,
       filename ="rGC_tree.pdf",
       device = cairo_pdf,
       width = 7)
    